project:
  type: website
  output-dir: docs

website:
  title: "Michał Śmielak"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: code.qmd
        text: Code
      - technology.qmd
      - posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

